In [1]:
import tensorflow as tf


In [2]:
print(tf.__version__)

2.19.0


Creating a tensor with tf.constant()


In [6]:
#Scaler
scaler=tf.constant(7)
print(scaler)

tf.Tensor(7, shape=(), dtype=int32)


In [15]:
print(scaler.ndim)
print(scaler.shape)

0
()


#Vector


In [8]:
vector=tf.constant([10,10])
print(vector)


tf.Tensor([10 10], shape=(2,), dtype=int32)


In [14]:
print(vector.ndim)
print(vector.shape)

1
(2,)


In [11]:
#Matrix

matrix=tf.constant([[10,7],
                   [7,10]])
print(matrix)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


In [13]:
print(matrix.ndim)
print(matrix.shape)

2
(2, 2)


In [27]:
#another matrix
another_matrix=tf.constant([[[1,2,3],
                             [4,5,6],
                             [7,8,9]]])
print(another_matrix)

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]], shape=(1, 3, 3), dtype=int32)


In [28]:
another_matrix.shape

TensorShape([1, 3, 3])