<a href="https://colab.research.google.com/github/FairozAhmadSheikh/Tensor_Flow/blob/main/01_creating_random_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf

In [8]:
random1=tf.random.Generator.from_seed(23)
random1=random1.normal(shape=(3,3))
random1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
       [ 0.4457582 ,  0.10944034, -0.8035768 ],
       [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>

In [9]:
random2=tf.random.Generator.from_seed(23)
random2=random2.normal(shape=(3,3))
random2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
       [ 0.4457582 ,  0.10944034, -0.8035768 ],
       [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>

As we have set same seed for both so both will be equal
`seed` is set for reproducibilty

In [10]:
random1,random2,random1==random2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.4457582 ,  0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.4457582 ,  0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

**Shuffle the order of Tensors** .............

***Shuffling the order of elemnets in Tensors**............

In [16]:
not_shuffled_tensor=tf.Variable([[1,2,3],[4,4,5],[6,1,3]])
not_shuffled_tensor

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 4, 5],
       [6, 1, 3]], dtype=int32)>

In [17]:
shuffled_tensor=tf.random.shuffle(not_shuffled_tensor)
shuffled_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 4, 5],
       [6, 1, 3],
       [1, 2, 3]], dtype=int32)>

Same order shuffuled Data.

In [18]:
new_not_shuffled=tf.random.Generator.from_seed(30)
new_not_shuffled=new_not_shuffled.uniform(shape=(3,3))
new_not_shuffled

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6900625 , 0.21108961, 0.00885725],
       [0.42452395, 0.08308113, 0.40762496],
       [0.5765996 , 0.49922466, 0.20822704]], dtype=float32)>

In [23]:
shuffled_one=tf.random.set_seed(20)
shuffled_one=tf.random.shuffle(new_not_shuffled,seed=20)
new_not_shuffled


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6900625 , 0.21108961, 0.00885725],
       [0.42452395, 0.08308113, 0.40762496],
       [0.5765996 , 0.49922466, 0.20822704]], dtype=float32)>