In [7]:
import tensorflow as tf

In [8]:
random1=tf.random.Generator.from_seed(23)
random1=random1.normal(shape=(3,3))
random1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
       [ 0.4457582 ,  0.10944034, -0.8035768 ],
       [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>

In [9]:
random2=tf.random.Generator.from_seed(23)
random2=random2.normal(shape=(3,3))
random2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
       [ 0.4457582 ,  0.10944034, -0.8035768 ],
       [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>

As we have set same seed for both so both will be equal
`seed` is set for reproducibilty

In [10]:
random1,random2,random1==random2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.4457582 ,  0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.4457582 ,  0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)