<a href="https://colab.research.google.com/github/FairozAhmadSheikh/Tensor_Flow/blob/main/01_creating_random_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
random1=tf.random.Generator.from_seed(23)
random1=random1.normal(shape=(3,3))
random1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
       [ 0.4457582 ,  0.10944034, -0.8035768 ],
       [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>

In [3]:
random2=tf.random.Generator.from_seed(23)
random2=random2.normal(shape=(3,3))
random2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
       [ 0.4457582 ,  0.10944034, -0.8035768 ],
       [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>

As we have set same seed for both so both will be equal
`seed` is set for reproducibilty

In [4]:
random1,random2,random1==random2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.4457582 ,  0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.4457582 ,  0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

**Shuffle the order of Tensors** .............

***Shuffling the order of elemnets in Tensors**............

In [5]:
not_shuffled_tensor=tf.Variable([[1,2,3],[4,4,5],[6,1,3]])
not_shuffled_tensor

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 4, 5],
       [6, 1, 3]], dtype=int32)>

In [6]:
shuffled_tensor=tf.random.shuffle(not_shuffled_tensor)
shuffled_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 4, 5],
       [6, 1, 3],
       [1, 2, 3]], dtype=int32)>

Same order shuffuled Data.

In [7]:
new_not_shuffled=tf.random.Generator.from_seed(30)
new_not_shuffled=new_not_shuffled.uniform(shape=(3,3))
new_not_shuffled

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6900625 , 0.21108961, 0.00885725],
       [0.42452395, 0.08308113, 0.40762496],
       [0.5765996 , 0.49922466, 0.20822704]], dtype=float32)>

In [8]:
shuffled_one=tf.random.set_seed(20)
shuffled_one=tf.random.shuffle(new_not_shuffled,seed=20)
new_not_shuffled


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.6900625 , 0.21108961, 0.00885725],
       [0.42452395, 0.08308113, 0.40762496],
       [0.5765996 , 0.49922466, 0.20822704]], dtype=float32)>

Other ways of Creating Tensor

<!-- Other ways of creating Tensor -->

In [9]:
tf.ones(shape=(10,10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [10]:
tf.ones([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

Turn numpy arrays into Tensors

In [11]:
import numpy as np

In [12]:
numpy_A=np.arange(1,11)

In [13]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
A=tf.constant(numpy_A)

In [15]:
A

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [16]:
B=tf.constant(numpy_A,shape=(5,2))
B

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])>

In [17]:
C=tf.constant(numpy_A,shape=(2,5))
C

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])>

In [18]:
tf.zeros([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [19]:
tf.zeros(shape=(10,10))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
tf.constant(np.arange(1,81),shape=(4,2,10))

<tf.Tensor: shape=(4, 2, 10), dtype=int64, numpy=
array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]],

       [[61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75, 76, 77, 78, 79, 80]]])>

## Getting Information From Tensors


In [26]:
# Creating a Rank 4 tensor
rank_4_tensor=tf.zeros(shape=[2,3,5,6])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 5, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.

In [27]:
rank_4_tensor.shape

TensorShape([2, 3, 5, 6])

In [28]:
rank_4_tensor.ndim

4

In [31]:
tf.size(rank_4_tensor).numpy()

np.int32(180)

In [33]:
2*3*5*6  # proof for size

180

Getting various attributes of the tensors

In [37]:
print("Data Type of every element ",rank_4_tensor.dtype)
print("Number of Dimensions (rank) ",rank_4_tensor.ndim)
print("Shape of Tensor ",rank_4_tensor.shape)
print('Elements along 0 axis',rank_4_tensor.shape[0])
print('Elements along last axis',rank_4_tensor.shape[-1])
print('Total elements or items in tensor ',tf.size(rank_4_tensor).numpy())


Data Type of every element  <dtype: 'float32'>
Number of Dimensions (rank)  4
Shape of Tensor  (2, 3, 5, 6)
Elements along 0 axis 2
Elements along last axis 6
Total elements or items in tensor  180


## Indexing and Expanding Tensors

In [38]:
# Getting first 2 elemets of each dimensions
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [39]:
# Getting First element from each Dimension except final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 6), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [40]:
rank_4_tensor[:1,:1,:1,]

<tf.Tensor: shape=(1, 1, 1, 6), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [42]:
(rank_4_tensor[:1,:1,:1,]  == rank_4_tensor[:1,:1,:1,:])

array([[[[ True,  True,  True,  True,  True,  True]]]])

In [43]:
rank_2_tensor=tf.constant([[1,2],
                           [3,4]])

In [45]:
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [48]:
# Get the last item of each of rank2 tensor
(rank_2_tensor[:,-1]).numpy()

array([2, 4], dtype=int32)

Adding an Extra Dimension  to the tensor

In [50]:
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [54]:
# Alternative way
# -1 means expand along 0 -axis
tf.expand_dims(rank_2_tensor,axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [55]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [56]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>