<a href="https://colab.research.google.com/github/FairozAhmadSheikh/Tensor_Flow/blob/main/AggregatingTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [6]:
tensor=tf.constant(np.random.randint(1,45,size=50))

In [7]:
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([15, 31,  1, 31, 34, 27, 17, 29, 35, 27,  8, 30, 11, 27, 38,  5,  2,
       27, 30,  9,  8, 15, 11,  1, 22, 38, 21, 27, 13,  2, 24,  2, 20, 12,
        7, 38,  5,  6, 18, 22,  9,  2, 17, 14, 28,  4,  4, 31, 31, 18])>


**Aggregating Tensors** : Condensing Tensors from multiple values to smaller values
1.   Finding Absolute values
2.   Min, Max, Mean, Standard Deviation, variance



In [8]:
neg_tesnor=tf.negative(tensor)

In [9]:
neg_tesnor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([-15, -31,  -1, -31, -34, -27, -17, -29, -35, -27,  -8, -30, -11,
       -27, -38,  -5,  -2, -27, -30,  -9,  -8, -15, -11,  -1, -22, -38,
       -21, -27, -13,  -2, -24,  -2, -20, -12,  -7, -38,  -5,  -6, -18,
       -22,  -9,  -2, -17, -14, -28,  -4,  -4, -31, -31, -18])>

In [10]:
tf.abs(neg_tesnor)

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([15, 31,  1, 31, 34, 27, 17, 29, 35, 27,  8, 30, 11, 27, 38,  5,  2,
       27, 30,  9,  8, 15, 11,  1, 22, 38, 21, 27, 13,  2, 24,  2, 20, 12,
        7, 38,  5,  6, 18, 22,  9,  2, 17, 14, 28,  4,  4, 31, 31, 18])>

In [16]:
# Min Max Mean Sum Standard div
print("the min of the tensor is : ",tf.reduce_min(tensor).numpy())
print("the max of the tensor is : ",tf.reduce_max(tensor).numpy())
print("the mean of the tensor is : ",tf.reduce_mean(tensor).numpy())
print("the sum of the tensor is : ",tf.reduce_sum(tensor).numpy())

the min of the tensor is :  1
the max of the tensor is :  38
the mean of the tensor is :  18
the sum of the tensor is :  904


In [17]:
tensor=tf.cast(tensor,dtype=tf.float32)
print("the standard devaition of the tensor is : ",tf.math.reduce_std(tensor).numpy())

the standard devaition of the tensor is :  11.462705


In [19]:
print("the variance of the tensor is : ",tf.math.reduce_variance(tensor).numpy())

the variance of the tensor is :  131.3936
