In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


**Tensor** is a vector or matrix that is is generalized to higher dimensions
**TensorFlow **represents tensors as n-dimensional arrays of base datatype
TF Programs work by building graphs of tensor objects that detail how tensors are related.
Then running different or all parts of the graphs allows results to be generated

In [3]:
# Creating Tensors

# String
string=tf.Variable("I am String ",tf.string)
# Number
number=tf.Variable(321,tf.int16)
# Float
floating=tf.Variable(22.6,tf.float16)

**Rank / Degree of a Tensor :** Simply means the number of dimensions involved in the tensor , What we created above all are rank1 Tensor

**Creating N Rank Tensors : ** (below)

In [23]:
rank1_tensor=tf.Variable(["Hello","Google","Yahoo"],tf.string)
rank2_tensor=tf.Variable([["I AM ","A","Coder"],["I LOVE ","JAVA","Script"],["no","yes","no"]],dtype=tf.string)
# To print Rank
# tf.rank(rank1_tensor)
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

**Shape of Tensor :** The number of elements of a tensor is the product of all the sizes of its shape which in simple word means the number of elements in a dimension


In [24]:
rank2_tensor.shape

TensorShape([3, 3])

**Changing shapes of a Tensor :** Below

In [32]:
t1=tf.ones([1,2,3]) # One internal list which consits two lists internally which internally  consists  of 3 elements
print(t1)
t2=tf.reshape(t1,[2,3,1])
print(t2)
t3=tf.reshape(t1,[3,2,1])
print(t3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)


**Types of Tensor:**
1: Variable
2: Constant
3: Placeholder
4: SpareTensor

With the Exception of **Variable**  all of the tensors are immutable , their value may not change during the execution



**Evalvating Tensor :**Since Tensors Represent a partially Complete Computation we will sometime need to run a session to Evalvate The Tensor.
Syntax:
with tf.Session() as sess:
  tensor_name.eval()