<a href="https://colab.research.google.com/github/FairozAhmadSheikh/Tensor_Flow/blob/main/Exploring_Tensorflow_and_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow interacts beutifully with numpy**

In [9]:
import tensorflow as tf
import numpy as np

In [10]:
# Create tensors beutifully with  numpy arrays
J=tf.constant(np.array([1,3,4,7,9]))
J

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 3, 4, 7, 9])>

In [11]:
# Convert Tensor back to array
np.array(J)

array([1, 3, 4, 7, 9])

In [12]:
# Check dtype
type(np.array(J))

numpy.ndarray

In [14]:
# Convert tensor J to numpy array
J.numpy(),J.numpy()[-1]

(array([1, 3, 4, 7, 9]), np.int64(9))

In [16]:
J=tf.constant([3.])
J.numpy()
J.numpy()[0]

np.float32(3.0)

# **Default datatypes are slightly differnt**

In [17]:
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

# **Finding access to GPU's**

In [18]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [1]:
import tensorflow as tf


In [2]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [3]:
tf.config.list_logical_devices("GPU")

[LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Sat Aug 30 17:03:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   57C    P0             29W /   70W |     102MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----