<a href="https://colab.research.google.com/github/FairozAhmadSheikh/Tensor_Flow/blob/main/Manipultating_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow Opeartions**


1. + , - ,* ,/




In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor=tf.constant(np.random.rand(),shape=[3,4])

In [ ]:
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.74845916, 0.74845916, 0.74845916, 0.74845916],
       [0.74845916, 0.74845916, 0.74845916, 0.74845916],
       [0.74845916, 0.74845916, 0.74845916, 0.74845916]], dtype=float32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[7.4845915, 7.4845915, 7.4845915, 7.4845915],
       [7.4845915, 7.4845915, 7.4845915, 7.4845915],
       [7.4845915, 7.4845915, 7.4845915, 7.4845915]], dtype=float32)>

In [ ]:
tensor +10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10.748459, 10.748459, 10.748459, 10.748459],
       [10.748459, 10.748459, 10.748459, 10.748459],
       [10.748459, 10.748459, 10.748459, 10.748459]], dtype=float32)>

In [ ]:
tensor /10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.07484592, 0.07484592, 0.07484592, 0.07484592],
       [0.07484592, 0.07484592, 0.07484592, 0.07484592],
       [0.07484592, 0.07484592, 0.07484592, 0.07484592]], dtype=float32)>

In [ ]:
tensor -.89

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.14154083, -0.14154083, -0.14154083, -0.14154083],
       [-0.14154083, -0.14154083, -0.14154083, -0.14154083],
       [-0.14154083, -0.14154083, -0.14154083, -0.14154083]],
      dtype=float32)>

# We can also use   built-in tensorflow functions to do the same

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[7.4845915, 7.4845915, 7.4845915, 7.4845915],
       [7.4845915, 7.4845915, 7.4845915, 7.4845915],
       [7.4845915, 7.4845915, 7.4845915, 7.4845915]], dtype=float32)>

In [ ]:
tf.add(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10.748459, 10.748459, 10.748459, 10.748459],
       [10.748459, 10.748459, 10.748459, 10.748459],
       [10.748459, 10.748459, 10.748459, 10.748459]], dtype=float32)>

In [ ]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-9.251541, -9.251541, -9.251541, -9.251541],
       [-9.251541, -9.251541, -9.251541, -9.251541],
       [-9.251541, -9.251541, -9.251541, -9.251541]], dtype=float32)>

In [ ]:
tf.divide(tensor,.89)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.8409654, 0.8409654, 0.8409654, 0.8409654],
       [0.8409654, 0.8409654, 0.8409654, 0.8409654],
       [0.8409654, 0.8409654, 0.8409654, 0.8409654]], dtype=float32)>

# Matrix Multiplication
*Rules for Matri Multiplication*
1.   Inner Dimensions must match
2.   Resulting Matrix must have a shape of outer dimensions





In [ ]:
X=tf.constant(np.random.randn(),shape=[3,3])
Y=tf.constant(np.random.randn(),shape=[3,2])
X,Y

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.07640224, -0.07640224, -0.07640224],
        [-0.07640224, -0.07640224, -0.07640224],
        [-0.07640224, -0.07640224, -0.07640224]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[2.117835, 2.117835],
        [2.117835, 2.117835],
        [2.117835, 2.117835]], dtype=float32)>)

In [ ]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.48542202, -0.48542202],
       [-0.48542202, -0.48542202],
       [-0.48542202, -0.48542202]], dtype=float32)>

In [ ]:
# Try to matrix Multiply of same shape

X=tf.constant(np.random.randint(10,22),shape=(3,2))
Y=tf.constant(np.random.randint(10,22),shape=(3,2))

X.shape,Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [ ]:
tf.matmul(X,Y)


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# Fixing above error
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[336, 336, 336],
       [336, 336, 336],
       [336, 336, 336]], dtype=int32)>

In [ ]:
# We can also fix it using tranpose
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[336, 336, 336],
       [336, 336, 336],
       [336, 336, 336]], dtype=int32)>

Same can be done using tf.tensordot

In [47]:
tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[336, 336, 336],
       [336, 336, 336],
       [336, 336, 336]], dtype=int32)>

In [48]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[336, 336, 336],
       [336, 336, 336],
       [336, 336, 336]], dtype=int32)>

In [49]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[336, 336, 336],
       [336, 336, 336],
       [336, 336, 336]], dtype=int32)>

In [53]:
# Silent Error Check Method
print('normal Y ')
print(Y,"\n")

normal Y 
tf.Tensor(
[[12 12]
 [12 12]
 [12 12]], shape=(3, 2), dtype=int32) 



In [54]:
print("Y reshaped to (2,3)")
print(tf.reshape(Y,shape=(2,3)),"\n")

Y reshaped to (2,3)
tf.Tensor(
[[12 12 12]
 [12 12 12]], shape=(2, 3), dtype=int32) 



In [56]:
print("Y transposed")
print(tf.transpose(Y))

Y transposed
tf.Tensor(
[[12 12 12]
 [12 12 12]], shape=(2, 3), dtype=int32)


In [ ]:
# Changing DataType of a Tensor