<a href="https://colab.research.google.com/github/FairozAhmadSheikh/Tensor_Flow/blob/main/Manipultating_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow Opeartions**


1. + , - ,* ,/




In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor=tf.constant(np.random.rand(),shape=[3,4])

In [3]:
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.10939229, 0.10939229, 0.10939229, 0.10939229],
       [0.10939229, 0.10939229, 0.10939229, 0.10939229],
       [0.10939229, 0.10939229, 0.10939229, 0.10939229]], dtype=float32)>

In [4]:
tensor*10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1.093923, 1.093923, 1.093923, 1.093923],
       [1.093923, 1.093923, 1.093923, 1.093923],
       [1.093923, 1.093923, 1.093923, 1.093923]], dtype=float32)>

In [5]:
tensor +10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10.109392, 10.109392, 10.109392, 10.109392],
       [10.109392, 10.109392, 10.109392, 10.109392],
       [10.109392, 10.109392, 10.109392, 10.109392]], dtype=float32)>

In [6]:
tensor /10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.01093923, 0.01093923, 0.01093923, 0.01093923],
       [0.01093923, 0.01093923, 0.01093923, 0.01093923],
       [0.01093923, 0.01093923, 0.01093923, 0.01093923]], dtype=float32)>

In [7]:
tensor -.89

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7806077, -0.7806077, -0.7806077, -0.7806077],
       [-0.7806077, -0.7806077, -0.7806077, -0.7806077],
       [-0.7806077, -0.7806077, -0.7806077, -0.7806077]], dtype=float32)>

# We can also use   built-in tensorflow functions to do the same

In [8]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1.093923, 1.093923, 1.093923, 1.093923],
       [1.093923, 1.093923, 1.093923, 1.093923],
       [1.093923, 1.093923, 1.093923, 1.093923]], dtype=float32)>

In [9]:
tf.add(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10.109392, 10.109392, 10.109392, 10.109392],
       [10.109392, 10.109392, 10.109392, 10.109392],
       [10.109392, 10.109392, 10.109392, 10.109392]], dtype=float32)>

In [10]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-9.890608, -9.890608, -9.890608, -9.890608],
       [-9.890608, -9.890608, -9.890608, -9.890608],
       [-9.890608, -9.890608, -9.890608, -9.890608]], dtype=float32)>

In [11]:
tf.divide(tensor,.89)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.12291269, 0.12291269, 0.12291269, 0.12291269],
       [0.12291269, 0.12291269, 0.12291269, 0.12291269],
       [0.12291269, 0.12291269, 0.12291269, 0.12291269]], dtype=float32)>

# Matrix Multiplication
*Rules for Matri Multiplication*
1.   Inner Dimensions must match
2.   Resulting Matrix must have a shape of outer dimensions





In [12]:
X=tf.constant(np.random.randn(),shape=[3,3])
Y=tf.constant(np.random.randn(),shape=[3,2])
X,Y

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.98185635, -0.98185635, -0.98185635],
        [-0.98185635, -0.98185635, -0.98185635],
        [-0.98185635, -0.98185635, -0.98185635]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.921627, 0.921627],
        [0.921627, 0.921627],
        [0.921627, 0.921627]], dtype=float32)>)

In [13]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-2.714716, -2.714716],
       [-2.714716, -2.714716],
       [-2.714716, -2.714716]], dtype=float32)>

In [14]:
# Try to matrix Multiply of same shape

X=tf.constant(np.random.randint(10,22),shape=(3,2))
Y=tf.constant(np.random.randint(10,22),shape=(3,2))

X.shape,Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [15]:
tf.matmul(X,Y)


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [16]:
# Fixing above error
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[756, 756, 756],
       [756, 756, 756],
       [756, 756, 756]], dtype=int32)>

In [17]:
# We can also fix it using tranpose
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[756, 756, 756],
       [756, 756, 756],
       [756, 756, 756]], dtype=int32)>

Same can be done using tf.tensordot

In [18]:
tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[756, 756, 756],
       [756, 756, 756],
       [756, 756, 756]], dtype=int32)>

In [19]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[756, 756, 756],
       [756, 756, 756],
       [756, 756, 756]], dtype=int32)>

In [20]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[756, 756, 756],
       [756, 756, 756],
       [756, 756, 756]], dtype=int32)>

In [22]:
# Silent Error Check Method
print('normal Y ')
print(Y,"\n")

normal Y 
tf.Tensor(
[[18 18]
 [18 18]
 [18 18]], shape=(3, 2), dtype=int32) 



In [23]:
print("Y reshaped to (2,3)")
print(tf.reshape(Y,shape=(2,3)),"\n")

Y reshaped to (2,3)
tf.Tensor(
[[18 18 18]
 [18 18 18]], shape=(2, 3), dtype=int32) 



In [24]:
print("Y transposed")
print(tf.transpose(Y))

Y transposed
tf.Tensor(
[[18 18 18]
 [18 18 18]], shape=(2, 3), dtype=int32)


In [26]:
# Changing DataType of a Tensor

N=tf.constant([10,2])


In [28]:
N.dtype

tf.int32

In [31]:
# int32 to float32 conversion
N_float=tf.cast(N,dtype=tf.float32)
N_float.dtype

tf.float32

In [33]:
N_float.numpy()

array([10.,  2.], dtype=float32)

In [34]:
N_float_16=tf.cast(N_float,dtype=tf.float16)
N_float_16.dtype

tf.float16