<a href="https://colab.research.google.com/github/FairozAhmadSheikh/Tensor_Flow/blob/main/Manipultating_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow Opeartions**


1. + , - ,* ,/




In [6]:
import tensorflow as tf
import numpy as np

In [11]:
tensor=tf.constant(np.random.rand(),shape=[3,4])

In [12]:
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.89918673, 0.89918673, 0.89918673, 0.89918673],
       [0.89918673, 0.89918673, 0.89918673, 0.89918673],
       [0.89918673, 0.89918673, 0.89918673, 0.89918673]], dtype=float32)>

In [13]:
tensor*10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[8.991867, 8.991867, 8.991867, 8.991867],
       [8.991867, 8.991867, 8.991867, 8.991867],
       [8.991867, 8.991867, 8.991867, 8.991867]], dtype=float32)>

In [14]:
tensor +10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10.899187, 10.899187, 10.899187, 10.899187],
       [10.899187, 10.899187, 10.899187, 10.899187],
       [10.899187, 10.899187, 10.899187, 10.899187]], dtype=float32)>

In [15]:
tensor /10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.08991867, 0.08991867, 0.08991867, 0.08991867],
       [0.08991867, 0.08991867, 0.08991867, 0.08991867],
       [0.08991867, 0.08991867, 0.08991867, 0.08991867]], dtype=float32)>

In [17]:
tensor -.89

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.00918674, 0.00918674, 0.00918674, 0.00918674],
       [0.00918674, 0.00918674, 0.00918674, 0.00918674],
       [0.00918674, 0.00918674, 0.00918674, 0.00918674]], dtype=float32)>

# We can also use   built-in tensorflow functions to do the same

In [18]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[8.991867, 8.991867, 8.991867, 8.991867],
       [8.991867, 8.991867, 8.991867, 8.991867],
       [8.991867, 8.991867, 8.991867, 8.991867]], dtype=float32)>

In [19]:
tf.add(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10.899187, 10.899187, 10.899187, 10.899187],
       [10.899187, 10.899187, 10.899187, 10.899187],
       [10.899187, 10.899187, 10.899187, 10.899187]], dtype=float32)>

In [20]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-9.100813, -9.100813, -9.100813, -9.100813],
       [-9.100813, -9.100813, -9.100813, -9.100813],
       [-9.100813, -9.100813, -9.100813, -9.100813]], dtype=float32)>

In [21]:
tf.divide(tensor,.89)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1.0103222, 1.0103222, 1.0103222, 1.0103222],
       [1.0103222, 1.0103222, 1.0103222, 1.0103222],
       [1.0103222, 1.0103222, 1.0103222, 1.0103222]], dtype=float32)>