<a href="https://colab.research.google.com/github/FairozAhmadSheikh/Tensor_Flow/blob/main/Manipultating_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tensorflow Opeartions**


1. + , - ,* ,/




In [23]:
import tensorflow as tf
import numpy as np

In [24]:
tensor=tf.constant(np.random.rand(),shape=[3,4])

In [25]:
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.74845916, 0.74845916, 0.74845916, 0.74845916],
       [0.74845916, 0.74845916, 0.74845916, 0.74845916],
       [0.74845916, 0.74845916, 0.74845916, 0.74845916]], dtype=float32)>

In [26]:
tensor*10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[7.4845915, 7.4845915, 7.4845915, 7.4845915],
       [7.4845915, 7.4845915, 7.4845915, 7.4845915],
       [7.4845915, 7.4845915, 7.4845915, 7.4845915]], dtype=float32)>

In [27]:
tensor +10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10.748459, 10.748459, 10.748459, 10.748459],
       [10.748459, 10.748459, 10.748459, 10.748459],
       [10.748459, 10.748459, 10.748459, 10.748459]], dtype=float32)>

In [28]:
tensor /10

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.07484592, 0.07484592, 0.07484592, 0.07484592],
       [0.07484592, 0.07484592, 0.07484592, 0.07484592],
       [0.07484592, 0.07484592, 0.07484592, 0.07484592]], dtype=float32)>

In [29]:
tensor -.89

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.14154083, -0.14154083, -0.14154083, -0.14154083],
       [-0.14154083, -0.14154083, -0.14154083, -0.14154083],
       [-0.14154083, -0.14154083, -0.14154083, -0.14154083]],
      dtype=float32)>

# We can also use   built-in tensorflow functions to do the same

In [30]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[7.4845915, 7.4845915, 7.4845915, 7.4845915],
       [7.4845915, 7.4845915, 7.4845915, 7.4845915],
       [7.4845915, 7.4845915, 7.4845915, 7.4845915]], dtype=float32)>

In [31]:
tf.add(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[10.748459, 10.748459, 10.748459, 10.748459],
       [10.748459, 10.748459, 10.748459, 10.748459],
       [10.748459, 10.748459, 10.748459, 10.748459]], dtype=float32)>

In [32]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-9.251541, -9.251541, -9.251541, -9.251541],
       [-9.251541, -9.251541, -9.251541, -9.251541],
       [-9.251541, -9.251541, -9.251541, -9.251541]], dtype=float32)>

In [33]:
tf.divide(tensor,.89)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.8409654, 0.8409654, 0.8409654, 0.8409654],
       [0.8409654, 0.8409654, 0.8409654, 0.8409654],
       [0.8409654, 0.8409654, 0.8409654, 0.8409654]], dtype=float32)>

# Matrix Multiplication
*Rules for Matri Multiplication*
1.   Inner Dimensions must match
2.   Resulting Matrix must have a shape of nner dimensions





In [38]:
X=tf.constant(np.random.randn(),shape=[3,3])
Y=tf.constant(np.random.randn(),shape=[3,2])
X,Y

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.07640224, -0.07640224, -0.07640224],
        [-0.07640224, -0.07640224, -0.07640224],
        [-0.07640224, -0.07640224, -0.07640224]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[2.117835, 2.117835],
        [2.117835, 2.117835],
        [2.117835, 2.117835]], dtype=float32)>)

In [39]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.48542202, -0.48542202],
       [-0.48542202, -0.48542202],
       [-0.48542202, -0.48542202]], dtype=float32)>